#
# Module manifest for module 'MyTools'
#
# Generated by: Frederic Vets
#
# Generated on: 16/05/2018
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'f4958eaa-9867-4c76-bcf2-e56ad081f9ee'

# Author of this module
Author = 'Frederic Vets'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2018 Frederic Vets. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Some standard utility cmdLets to : get the size of a file / folder, convert between size units, suspend / hibernate the current machine ...'

# Minimum version of the Windows PowerShell engine required by this module
# Version 5 since it uses classes.
PowerShellVersion = '5.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# This assembly is required by the Set-PowerState function.
RequiredAssemblies = @('System.Windows.Forms')

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# Order in which to import is important (e.g. Prefix.ps1 references constants defined in Unit.ps1)
NestedModules = @(
    'aliases.ps1',
    'Classes\Size\PrefixType.ps1',
    'Classes\Size\UnitType.ps1',
    'Classes\Size\Prefix.ps1',
    'Classes\Size\Unit.ps1',
    'Private\Size\Configuration.ps1',
    'Public\Convert-Size.ps1',
    'Public\Get-Size.ps1',
    'Public\Get-SizeConverted.ps1',
    'Public\Update-File.ps1',
    'Public\Set-PowerState.ps1',
    'Public\Get-ConfirmImpact.ps1'
)

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Convert-Size', 
    'Get-Size', 
    'Get-SizeConverted', 
    'Update-File',
    'Set-PowerState',
        'Suspend-Computer',
        'Hibernate-Computer',
    'Get-ConfirmImpact'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = '*'
VariablesToExport = ''


# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @('gsc')

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# The ModuleList key is designed to act as a module inventory. These modules are not automatically processed.
# ModuleList = @()

# List of all files packaged with this module
# FileList is to assist you as an inventory list, and is not otherwise processed.
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}